### PR TITLE
Add package.json for npm

### PR DESCRIPTION
**Pull request by jamiebuilds**
I would like to be able to consume this library from [npm](https://www.npmjs.com).

This PR adds a `package.json` file to the repo which points to the `src/index.js` file as the entry point.

Would you mind merging this and publishing on npm? Here is the docs on how to do it: https://docs.npmjs.com/getting-started/publishing-npm-packages

### CODE REVIEW

**Comment by IanSaunders** [comment]
@thejameskyle Thanks for the request. Will review with @billforward-alex and get back to you.

**Comment by Birch-san** [comment]
Hm, I think a huge amount of the functionality here relies on a DOM's being present. i.e. user interaction, embedding of hosted forms, collecting device metadata…

Would it suffice to just to install it from your own fork like so:

``` bash
npm install git+ssh://git@github.com:thejameskyle/billforward-js.git --save
```

Otherwise: presumably `bower` or a CDN would be more suitable for client-side libraries?

Is there something in particular you're trying to do with card capture in Node? If you're already server-side, then you can use server-side card capture techniques (i.e. the API of your gateway).

If you're trying to do server -> BillForward (and you already have a nonce from Braintree, or the raw credit card details) you can call the BillForward API directly from your server. For example, with Braintree:

(using nonce) note — you should authenticate using your _public_ token
https://app-sandbox.billforward.net/#/api/method/tokenization/POST?input_discriminator=BraintreeAuthCaptureRequest&path=%252Ftokenization%252Fauth-capture&fosterMethodName=tokenization

(with raw card details) — private token; must be performed server-side
https://app-sandbox.billforward.net/#/api/method/tokenization/POST?path=%252Ftokenization%252Fbraintree

**Comment by jamiebuilds** [comment]
>  huge amount of the functionality here relies on a DOM's being present...something in particular you're trying to do with card capture in Node

I'm not using npm for server-side code, it works just as well for client-side libraries. We bundle our dependencies with http://browserify.org.

**Comment by Birch-san** [comment]
Okay, if it's just for Browserify then that's fine. Seems harmless enough to merge in.

**Comment by jamiebuilds** [comment]
Are you okay publishing new versions as you update stuff?

**Comment by Birch-san** [comment]
Hm, that's a bit trickier — often I'm just making one-line changes straight to master.
Might be overkill to bump package.json every time.
Is it a problem to spam-publish minor revisions?

For most of our repositories, releases are done in response to a customer use-case or discussion, and mostly use whatever release mechanism that particular stakeholder prefers.

Another thought:
If I merge this `package.json` in, you still have the power to grab the latest commit automatically without any release process, just by pointing to HEAD of `master` (which is the default):

``` bash
npm install git+ssh://git@github.com:billforward/billforward-js.git
```

I think we've so far steered clear of breaking changes, so going for the latest commit always works pretty well.

**Comment by jamiebuilds** [comment]
It's totally fine to:

```
$ npm version patch
$ npm publish
$ git push origin master --follow-tags
```

As much as you want, I've published modules a half dozen times a day.

> I think we've so far steered clear of breaking changes, so going for the latest commit always works pretty well.

I trust that you do a good job with breaking changes, but I'm definitely not going to point to the HEAD of master as that's unnecessary risk.

It's just nicer to be able to do:

``` sh
$ npm outdated
Package          Current  Wanted  Latest  Location
billforward-js     x.x.x   x.x.x   x.x.x  repo-name
```

And bump it when I want to so it can be tested out. Otherwise it could break unpredictably if you do happen to do something wrong, and our billing process breaking randomly would be a massive issue.

**Comment by billforward-alex** [comment]
[We are now on `npm`](https://www.npmjs.com/package/billforward-js), and README has been updated to reflect how to perform minor-revision releases.

**Pull request merged**
